import { z } from "zod";

const coerceBool = z.preprocess((val) => {
  if (typeof val === 'boolean') return val;
  if (val === 'true' || val === 'on' || val === '1') return true;
  if (val === 'false' || val === 'off' || val === '0' || val === '' || val === null || val === undefined) return false;
  return Boolean(val);
}, z.boolean());

export const SettingsSchema = z.object({
  riskProfile: z.enum(["low", "medium", "high", "degen"]).default("medium"),
  executionMode: z.enum(["paper", "live"]).default("paper"),
  loopSeconds: z.number().int().min(5).max(3600).default(60),
  maxDailyDrawdownPct: z.number().min(0).max(0.99).default(0.05),
  maxPositionPctPerAsset: z.number().min(0.01).max(0.99).default(0.25),
  maxTurnoverPctPerDay: z.number().min(0.1).max(1000).default(1.0),
  maxSlippageBps: z.number().int().min(1).max(2000).default(80),
  maxSingleSwapSol: z.number().min(0.01).max(1000).default(1.5),
  minTradeUsd: z.number().min(1).max(1000000).default(25),
  maxPositions: z.number().int().min(1).max(100).default(10),
  maxTop3ConcentrationPct: z.number().min(0.1).max(1.0).default(0.70),
  maxPortfolioVolatility: z.number().min(0.1).max(100).default(0.50),
  takeProfitPct: z.number().min(0).max(10).default(0.05),
  scannerMinLiquidity: z.number().min(0).default(10000),
  scannerMinVolume24h: z.number().min(0).default(5000),
  scannerMinHolders: z.number().int().min(0).default(100),
  scannerMaxPriceChange24h: z.number().default(500),
  scannerMinPriceChange24h: z.number().default(-50),
  manualPause: coerceBool.default(false),
  coreSlots: z.number().int().min(1).max(50).default(5),
  scoutSlots: z.number().int().min(1).max(100).default(10),
  corePositionPctTarget: z.number().min(0.01).max(0.5).default(0.12),
  scoutPositionPct: z.number().min(0.005).max(0.2).default(0.03),
  rotationThreshold: z.number().min(0.1).max(10).default(1.5),
  stalePositionHours: z.number().int().min(1).max(720).default(48),
  staleExitHours: z.number().int().min(1).max(720).default(72),
  trailingStopBasePct: z.number().min(0.01).max(1).default(0.30),
  trailingStopTightPct: z.number().min(0.01).max(1).default(0.12),
  trailingStopProfitThreshold: z.number().min(0).max(10).default(0.50),
  rankingSignalWeight: z.number().default(3.0),
  rankingMomentumWeight: z.number().default(2.0),
  rankingTimeDecayWeight: z.number().default(1.0),
  rankingTrailingWeight: z.number().default(2.5),
  rankingFreshnessWeight: z.number().default(1.5),
  rankingQualityWeight: z.number().default(1.0),
  rankingStalePenalty: z.number().default(-2.0),
  rankingTrailingStopPenalty: z.number().default(-10.0),
  reentryEnabled: coerceBool.default(true),
  reentryCooldownMinutes: z.number().int().min(1).max(1440).default(3),
  reentryWindowMinutes: z.number().int().min(1).max(1440).default(30),
  reentryMinMomentumScore: z.number().default(1.0),
  reentrySizeMultiplier: z.number().min(0.1).max(10).default(3.0),
  reentryMaxSolPct: z.number().min(0.01).max(1).default(0.5),
  promotionMinPnlPct: z.number().min(0).max(10).default(0.20),
  promotionMinSignalScore: z.number().default(2.0),
  strategyTrendThreshold: z.number().min(0).max(1).default(0.75),
  strategyMomentumFactor: z.number().min(0).max(1).default(0.25),
  strategyBand: z.number().min(0).max(1).default(0.05),
  concentrationRebalanceMaxPct: z.number().min(0.01).max(1).default(0.25),
  transferThresholdUsd: z.number().min(0).default(5),
  autonomousScoutsEnabled: coerceBool.default(false),
  autonomousDryRun: coerceBool.default(true),
  scoutAutoQueueScore: z.number().int().min(1).max(100).default(10),
  scoutBuySol: z.number().min(0.001).max(10).default(0.02),
  minSolReserve: z.number().min(0).max(100).default(0.1),
  scoutTokenCooldownHours: z.number().int().min(1).max(168).default(24),
  scoutDailyLimit: z.number().int().min(1).max(1000000).default(5),
  scoutQueuePollSeconds: z.number().int().min(10).max(3600).default(60),
  scoutQueueStaleMinutes: z.number().int().min(1).max(60).default(5),
  scoutQueueMaxBuyAttempts: z.number().int().min(1).max(10).default(3),
  scanIntervalMinutes: z.number().int().min(1).max(60).default(5),
  // Whale confirmation feature flags
  whaleConfirmEnabled: coerceBool.default(false),
  whaleConfirmDryRun: coerceBool.default(true),
  whaleConfirmPollSeconds: z.number().int().min(10).max(300).default(30),
  whaleWindowMinutes: z.number().int().min(1).max(60).default(10),
  whaleMinUsd: z.number().min(100).max(100000).default(5000),
  whaleNetflowTriggerUsd: z.number().min(100).max(1000000).default(8000),
  marketConfirmPct: z.number().min(0).max(50).default(1.5),
  maxPriceImpactBps: z.number().int().min(10).max(1000).default(150),
  exitNetflowUsd: z.number().min(-1000000).max(0).default(-7000),
  exitTrailDrawdownPct: z.number().min(1).max(50).default(8),
  scoutUnderperformMinutes: z.number().int().min(10).max(1440).default(180),
  whaleCooldownMinutes: z.number().int().min(1).max(1440).default(60),
  // Advanced Flow Controls - expose previously hardcoded values
  stalePnlBandPct: z.number().min(0).max(0.5).default(0.05),
  dustThresholdUsd: z.number().min(0).max(10).default(0.50),
  minPositionUsd: z.number().min(0).max(100).default(1.0),
  txFeeBufferSol: z.number().min(0).max(0.5).default(0.01),
  scoutStopLossPct: z.number().min(0).max(1).default(0.18),
  lossExitPct: z.number().min(0).max(1).default(0.15),
  promotionDelayMinutes: z.number().int().min(0).max(1440).default(15),
  scoutGraceMinutes: z.number().int().min(0).max(1440).default(10),
  manualScoutBuyEnabled: coerceBool.default(true),
  minTicksForSignals: z.number().int().min(5).max(500).default(60),
  // Allocation Ramp - prevents over-allocation on low tick count tokens
  allocationRampEnabled: coerceBool.default(true),
  minTicksForFullAlloc: z.number().int().min(0).max(500).default(30),
  preFullAllocMaxPct: z.number().min(0).max(1).default(0.08),
  smoothRamp: coerceBool.default(true),
  hardCapBeforeFull: coerceBool.default(true),
  // Exit Invariant - ensures positions close completely
  exitInvariantEnabled: coerceBool.default(true),
  exitInvariantMaxRetries: z.number().int().min(1).max(5).default(2),
  exitInvariantRetryDelayMs: z.number().int().min(500).max(5000).default(1200),
  exitInvariantMinRemainingQty: z.number().min(0).max(1000000).default(0),
  exitInvariantMinRemainingUsd: z.number().min(0.10).max(100).default(0.50),
  exitInvariantSlippageBps: z.number().int().min(50).max(1000).default(300),
  exitInvariantForceExactClose: coerceBool.default(false),
  // Scout Entry - No-chase + Pullback gating
  scoutChaseRet15Max: z.number().min(0).max(1).default(0.25),
  scoutImpulseRet15Min: z.number().min(0).max(1).default(0.10),
  scoutPullbackFromHigh15Min: z.number().min(0).max(1).default(0.08),
  scoutEntrySmaMinutes: z.number().int().min(5).max(120).default(30),
  scoutEntryRequireAboveSma: coerceBool.default(true),
  scoutEntryTrendSmaMinutes: z.number().int().min(30).max(1440).default(240),
  // Scout Exit - Volatility harvest TP settings
  scoutTakeProfitPct: z.number().min(0).max(1).default(0.10),
  scoutTpMinHoldMinutes: z.number().int().min(0).max(60).default(5),
  // Promotion - Continuation-only with avoid-top filter
  promotionMinHoursHeld: z.number().min(0).max(24).default(1),
  promotionRequireRet60Min: z.number().min(-1).max(1).default(0.10),
  promotionRequireRet15Min: z.number().min(-1).max(1).default(0.00),
  promotionAvoidTopDrawdown30: z.number().min(0).max(0.5).default(0.03),
  promotionSmaMinutes: z.number().int().min(5).max(120).default(60),
  promotionRequireAboveSma: coerceBool.default(true),
  // Price fetch optimization - skip dust tokens
  minPositionUsdForPricing: z.number().min(0).default(1),
  maxPriceFetchMints: z.number().int().min(10).max(1000).default(250),
  equityPriceCoverageMin: z.number().min(0).max(1).default(0.75),
  equityPriceCoverageMinUsd: z.number().min(0).default(1.00),
  executionPriceCoverageMin: z.number().min(0).max(1).default(0.60),
});

export type Settings = z.infer<typeof SettingsSchema>;

export const SettingsDefaults: Settings = SettingsSchema.parse({});

export function normalizeSettings(raw: Partial<Settings>): Settings {
  const merged = { ...SettingsDefaults, ...raw };
  return SettingsSchema.parse(merged);
}

export const camelToSnakeMapping: Record<keyof Settings, string> = {
  riskProfile: "risk_profile",
  executionMode: "execution_mode",
  loopSeconds: "loop_seconds",
  maxDailyDrawdownPct: "max_daily_drawdown_pct",
  maxPositionPctPerAsset: "max_position_pct_per_asset",
  maxTurnoverPctPerDay: "max_turnover_pct_per_day",
  maxSlippageBps: "max_slippage_bps",
  maxSingleSwapSol: "max_single_swap_sol",
  minTradeUsd: "min_trade_usd",
  maxPositions: "max_positions",
  maxTop3ConcentrationPct: "max_top3_concentration_pct",
  maxPortfolioVolatility: "max_portfolio_volatility",
  takeProfitPct: "take_profit_pct",
  scannerMinLiquidity: "scanner_min_liquidity",
  scannerMinVolume24h: "scanner_min_volume_24h",
  scannerMinHolders: "scanner_min_holders",
  scannerMaxPriceChange24h: "scanner_max_price_change_24h",
  scannerMinPriceChange24h: "scanner_min_price_change_24h",
  manualPause: "manual_pause",
  coreSlots: "core_slots",
  scoutSlots: "scout_slots",
  corePositionPctTarget: "core_position_pct_target",
  scoutPositionPct: "scout_position_pct",
  rotationThreshold: "rotation_threshold",
  stalePositionHours: "stale_position_hours",
  staleExitHours: "stale_exit_hours",
  trailingStopBasePct: "trailing_stop_base_pct",
  trailingStopTightPct: "trailing_stop_tight_pct",
  trailingStopProfitThreshold: "trailing_stop_profit_threshold",
  rankingSignalWeight: "ranking_signal_weight",
  rankingMomentumWeight: "ranking_momentum_weight",
  rankingTimeDecayWeight: "ranking_time_decay_weight",
  rankingTrailingWeight: "ranking_trailing_weight",
  rankingFreshnessWeight: "ranking_freshness_weight",
  rankingQualityWeight: "ranking_quality_weight",
  rankingStalePenalty: "ranking_stale_penalty",
  rankingTrailingStopPenalty: "ranking_trailing_stop_penalty",
  reentryEnabled: "reentry_enabled",
  reentryCooldownMinutes: "reentry_cooldown_minutes",
  reentryWindowMinutes: "reentry_window_minutes",
  reentryMinMomentumScore: "reentry_min_momentum_score",
  reentrySizeMultiplier: "reentry_size_multiplier",
  reentryMaxSolPct: "reentry_max_sol_pct",
  promotionMinPnlPct: "promotion_min_pnl_pct",
  promotionMinSignalScore: "promotion_min_signal_score",
  strategyTrendThreshold: "strategy_trend_threshold",
  strategyMomentumFactor: "strategy_momentum_factor",
  strategyBand: "strategy_band",
  concentrationRebalanceMaxPct: "concentration_rebalance_max_pct",
  transferThresholdUsd: "transfer_threshold_usd",
  autonomousScoutsEnabled: "autonomous_scouts_enabled",
  autonomousDryRun: "autonomous_dry_run",
  scoutAutoQueueScore: "scout_auto_queue_score",
  scoutBuySol: "scout_buy_sol",
  minSolReserve: "min_sol_reserve",
  scoutTokenCooldownHours: "scout_token_cooldown_hours",
  scoutDailyLimit: "scout_daily_limit",
  scoutQueuePollSeconds: "scout_queue_poll_seconds",
  scoutQueueStaleMinutes: "scout_queue_stale_minutes",
  scoutQueueMaxBuyAttempts: "scout_queue_max_buy_attempts",
  scanIntervalMinutes: "scan_interval_minutes",
  // Whale confirmation feature flags
  whaleConfirmEnabled: "whale_confirm_enabled",
  whaleConfirmDryRun: "whale_confirm_dry_run",
  whaleConfirmPollSeconds: "whale_confirm_poll_seconds",
  whaleWindowMinutes: "whale_window_minutes",
  whaleMinUsd: "whale_min_usd",
  whaleNetflowTriggerUsd: "whale_netflow_trigger_usd",
  marketConfirmPct: "market_confirm_pct",
  maxPriceImpactBps: "max_price_impact_bps",
  exitNetflowUsd: "exit_netflow_usd",
  exitTrailDrawdownPct: "exit_trail_drawdown_pct",
  scoutUnderperformMinutes: "scout_underperform_minutes",
  whaleCooldownMinutes: "whale_cooldown_minutes",
  // Advanced Flow Controls
  stalePnlBandPct: "stale_pnl_band_pct",
  dustThresholdUsd: "dust_threshold_usd",
  minPositionUsd: "min_position_usd",
  txFeeBufferSol: "tx_fee_buffer_sol",
  scoutStopLossPct: "scout_stop_loss_pct",
  lossExitPct: "loss_exit_pct",
  promotionDelayMinutes: "promotion_delay_minutes",
  scoutGraceMinutes: "scout_grace_minutes",
  manualScoutBuyEnabled: "manual_scout_buy_enabled",
  minTicksForSignals: "min_ticks_for_signals",
  allocationRampEnabled: "allocation_ramp_enabled",
  minTicksForFullAlloc: "min_ticks_for_full_alloc",
  preFullAllocMaxPct: "pre_full_alloc_max_pct",
  smoothRamp: "smooth_ramp",
  hardCapBeforeFull: "hard_cap_before_full",
  // Exit Invariant
  exitInvariantEnabled: "exit_invariant_enabled",
  exitInvariantMaxRetries: "exit_invariant_max_retries",
  exitInvariantRetryDelayMs: "exit_invariant_retry_delay_ms",
  exitInvariantMinRemainingQty: "exit_invariant_min_remaining_qty",
  exitInvariantMinRemainingUsd: "exit_invariant_min_remaining_usd",
  exitInvariantSlippageBps: "exit_invariant_slippage_bps",
  exitInvariantForceExactClose: "exit_invariant_force_exact_close",
  // Scout Entry - No-chase + Pullback gating
  scoutChaseRet15Max: "scout_chase_ret15_max",
  scoutImpulseRet15Min: "scout_impulse_ret15_min",
  scoutPullbackFromHigh15Min: "scout_pullback_from_high15_min",
  scoutEntrySmaMinutes: "scout_entry_sma_minutes",
  scoutEntryRequireAboveSma: "scout_entry_require_above_sma",
  scoutEntryTrendSmaMinutes: "scout_entry_trend_sma_minutes",
  // Scout Exit - Volatility harvest TP
  scoutTakeProfitPct: "scout_take_profit_pct",
  scoutTpMinHoldMinutes: "scout_tp_min_hold_minutes",
  // Promotion - Continuation-only with avoid-top filter
  promotionMinHoursHeld: "promotion_min_hours_held",
  promotionRequireRet60Min: "promotion_require_ret60_min",
  promotionRequireRet15Min: "promotion_require_ret15_min",
  promotionAvoidTopDrawdown30: "promotion_avoid_top_drawdown30",
  promotionSmaMinutes: "promotion_sma_minutes",
  promotionRequireAboveSma: "promotion_require_above_sma",
  minPositionUsdForPricing: "min_position_usd_for_pricing",
  maxPriceFetchMints: "max_price_fetch_mints",
  equityPriceCoverageMin: "equity_price_coverage_min",
  equityPriceCoverageMinUsd: "equity_price_coverage_min_usd",
  executionPriceCoverageMin: "execution_price_coverage_min",
};

export function snakeToCamelMapping(): Record<string, keyof Settings> {
  const result: Record<string, keyof Settings> = {};
  for (const [camel, snake] of Object.entries(camelToSnakeMapping)) {
    result[snake] = camel as keyof Settings;
  }
  return result;
}
